
default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: expenses
  username: postgres
  password: 000000
  host: localhost
  port: 5432


test:
  <<: *default
  database: expenses
  username: postgres
  password: 000000
  host: localhost
  port: 5432

production:
  <<: *default

