require 'dotenv'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: expenses
  username: postgres
  password: 000000
  host: localhost
  port: 5432


test:
  <<: *development

production:
  url: <%= ENV['DATABASE_URL'] %>

